### PR TITLE
Update to reflect that this is in official plugin channel

### PR DESCRIPTION
**Pull request by KronosTheLate**
I have just done this myself ^_^

### CODE REVIEW

**Comment by masflam** [comment]
Thanks!

**Comment by KronosTheLate** [comment]
Wow, that was impressively fast for a project that has not been touched for 3 years xD

**Comment by masflam** [comment]
I'm not exactly that busy with anything else either hah
I myself have a PR on a repo that hasn't been acknowledged in 2 years or so, so I know how annoying it is :)

**Comment by KronosTheLate** [comment]
Well good luck on your PR xD

**Pull request merged**
